datasets:
  cyto_vqa: # name of the dataset builder
    dataset_card: dataset_card/cyto_vqa.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: ManualRevise/train_all_remove_class.json
          storage: ManualRevise/train_all_remove_class.json
#        val:
#          url: Cyto/sfy1_part/all_labels_W_class/val.json
#          storage: Cyto/sfy1_part/all_labels_W_class/val.json
#        test:
#          url: Cyto/sfy1_part/all_labels_W_class/test.json
#          storage: Cyto/sfy1_part/all_labels_W_class/test.json
      images:
        storage: image
