 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  cyto_caption: # name of the dataset builder
    dataset_card: dataset_card/cyto_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: AutoRevise/train_remove_class.json
          storage: AutoRevise/train_remove_class.json
#        val:
#          url: Cyto/TBS/annotations/all_label.json
#          storage:  Cyto/TBS/annotations/all_label.json
#        test:
#          url: Cyto/TBS/annotations/all_label.json
#          storage: Cyto/TBS/annotations/all_label.json   #/mnt/media_nvme/Process/CytoGPT/Data/Cyto/annotations/all_label.json
      images:
        storage: image

